### ISSUE TITLE
ImportError: cannot import name 'get_num_classes' from 'torchmetrics.utilities.data' (/usr/local/lib/python3.8/dist-packages/torchmetrics/utilities/data.py)

### ISSUE THREAD

**Issue by Mr-Ye-Cao** [Green-Wood/BTTR#14]
Traceback (most recent call last):
  File "train.py", line 1, in <module>
    from pytorch_lightning.utilities.cli import LightningCLI
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/__init__.py", line 20, in <module>
    from pytorch_lightning import metrics  # noqa: E402
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/metrics/__init__.py", line 15, in <module>
    from pytorch_lightning.metrics.classification import (  # noqa: F401
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/metrics/classification/__init__.py", line 14, in <module>
    from pytorch_lightning.metrics.classification.accuracy import Accuracy  # noqa: F401
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/metrics/classification/accuracy.py", line 18, in <module>
    from pytorch_lightning.metrics.utils import deprecated_metrics
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/metrics/utils.py", line 22, in <module>
    from torchmetrics.utilities.data import get_num_classes as _get_num_classes
ImportError: cannot import name 'get_num_classes' from 'torchmetrics.utilities.data' (/usr/local/lib/python3.8/dist-packages/torchmetrics/utilities/data.py)

**Comment by jordanandrade7** [comment]
upgrade your pytorch-lightning to1.5.10, you can use this command: pip install pytorch-lightning==1.5.10

**Comment by vishnu-keyvalue** [comment]
@jordanandrade7 I upgraded pytorch-lightning to 1.5.10 and retried, howver receiving another error while running train.py

```
Traceback (most recent call last):
  File "train.py", line 1, in <module>
    from pytorch_lightning.utilities.cli import LightningCLI
  File "/opt/anaconda3/envs/bttr/lib/python3.7/site-packages/pytorch_lightning/utilities/cli.py", line 35, in <module>
    from jsonargparse import ActionConfigFile, ArgumentParser, class_from_function, set_config_read_mode
ImportError: cannot import name 'class_from_function' from 'jsonargparse' (/opt/anaconda3/envs/bttr/lib/python3.7/site-packages/jsonargparse/__init__.py)
```
