### ISSUE TITLE
test.py error occurs

### ISSUE THREAD

**Issue by ai-motive** [Green-Wood/BTTR#2]
When I run test.py code, the following error occurs. Can i get some helps?

in test.py code
test_year = "2016"
ckp_path = "pretrained model"

```
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
Load data from: /home/motive/PycharmProjects/BTTR/bttr/datamodule/../../data.zip
Extract data from: 2016, with data size: 1147
total  1147 batch data loaded
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
Testing: 100%|██████████| 1147/1147 [07:34<00:00,  2.01s/it]ExpRate: 0.32258063554763794
length of total file: 1147
Testing: 100%|██████████| 1147/1147 [07:34<00:00,  2.52it/s]
--------------------------------------------------------------------------------
DATALOADER:0 TEST RESULTS
{}
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/motive/PycharmProjects/BTTR/test.py", line 17, in <module>
    trainer.test(model, datamodule=dm)
  File "/home/motive/anaconda3/envs/bttr/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 579, in test
    results = self._run(model)
  File "/home/motive/anaconda3/envs/bttr/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 759, in _run
    self.post_dispatch()
  File "/home/motive/anaconda3/envs/bttr/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 789, in post_dispatch
    self.accelerator.teardown()
  File "/home/motive/anaconda3/envs/bttr/lib/python3.7/site-packages/pytorch_lightning/accelerators/gpu.py", line 51, in teardown
    self.lightning_module.cpu()
  File "/home/motive/anaconda3/envs/bttr/lib/python3.7/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 141, in cpu
    return super().cpu()
  File "/home/motive/anaconda3/envs/bttr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 471, in cpu
    return self._apply(lambda t: t.cpu())
  File "/home/motive/anaconda3/envs/bttr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  File "/home/motive/anaconda3/envs/bttr/lib/python3.7/site-packages/torchmetrics/metric.py", line 317, in _apply
    setattr(this, key, [fn(cur_v) for cur_v in current_val])
  File "/home/motive/anaconda3/envs/bttr/lib/python3.7/site-packages/torchmetrics/metric.py", line 317, in <listcomp>
    setattr(this, key, [fn(cur_v) for cur_v in current_val])
  File "/home/motive/anaconda3/envs/bttr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 471, in <lambda>
    return self._apply(lambda t: t.cpu())
AttributeError: 'tuple' object has no attribute 'cpu'
```

**Comment by Green-Wood** [comment]
Could you provide more information about your `lit_bttr.py` file? It seems that you have changed the `test_epoch_end` part of it.

Notice that the return value of `self.result_recorder.compute()` function is already a list of tuple. So you can directly use it without using the `.cpu()`.

**Comment by ai-motive** [comment]
I didn't change `lit_bttr.py`
this is my file link : https://github.com/ai-motive/BTTR/blob/main/bttr/lit_bttr.py

when i run `test.py` code, model was set to 'cpu'. (mode..device.type='cpu'). I don't understand this part.
![스크린샷, 2021-05-20 23-56-49](https://user-images.githubusercontent.com/69468134/119001665-24aed480-b9c7-11eb-99e8-d25b1db1dfbb.png)

And i checked the results list in the `trainer.test()`  was empty.

**Comment by Green-Wood** [comment]
Thank you for pointing out that problem. We found out that this error is caused by using pytorch-lightning 1.3.0rc1 as our dev version. 

Now we’ve fixed our code in `lit_bttr.py` and `requirements.txt`. You can see we changed the way to collect result in the test phase.
